modLoader       = "javafml"
loaderVersion   = "[${forge_loader_version},)"
license         = "${mod_license}"
issueTrackerURL = "${mod_issue_tracker_url}"

[[mods]]
modId       = "${mod_id}"
version     = "${mod_version}"
displayName = "${mod_name}"
displayURL  = "${mod_display_url}"
logoFile    = "icon.png"
authors     = "${mod_authors}"

# The description text for the mod (multi line!) (#mandatory)
description = '''
${mod_description}
'''

[[dependencies.potmeetkettle]]
modId        = "forge"
mandatory    = true
versionRange = "[${forge_api_version},)"
ordering     = "NONE"
side         = "BOTH"

[[dependencies.potmeetkettle]]
modId        = "minecraft"
mandatory    = true
versionRange = "[${minecraft_version},)"
ordering     = "NONE"
side         = "BOTH"
