modLoader       = "javafml"
loaderVersion   = "[r-forge_loader_version-r,)"
license         = "r-mod_license-r"
issueTrackerURL = "r-mod_issue_tracker_url-r"

[[mods]]
modId       = "r-mod_id-r"
version     = "r-mod_version-r"
displayName = "r-mod_name-r"
displayURL  = "r-mod_display_url-r"
logoFile    = "icon.png"
authors     = "r-mod_authors-r"

# The description text for the mod (multi line!) (#mandatory)
description = '''
r-mod_description-r
'''

[[dependencies.potmeetkettle]]
modId        = "forge"
mandatory    = true
versionRange = "[r-forge_api_version-r,)"
ordering     = "NONE"
side         = "BOTH"

[[dependencies.potmeetkettle]]
modId        = "minecraft"
mandatory    = true
versionRange = "[r-minecraft_version-r,)"
ordering     = "NONE"
side         = "BOTH"
